StudentMedicalCertificateSystem/Models/Diagnosis.cs
using System.ComponentModel.DataAnnotations;

namespace StudentMedicalCertificateSystem.Models
{
    public class Diagnosis
    {
        [Key]
        public int DiagnosisID { get; set; }
        public string? DiagnosisName { get; set; }
        public string? Code { get; set; }
    }
}

StudentMedicalCertificateSystem/Controllers/DiagnosisController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudentMedicalCertificateSystem.Interfaces;
using StudentMedicalCertificateSystem.Models;
using StudentMedicalCertificateSystem.Repository;

namespace StudentMedicalCertificateSystem.Controllers
{
    [Authorize(Policy = "UserOrAdminPolicy")]
    public class DiagnosisController : Controller
    {
        private readonly IDiagnosisRepository _diagnosisRepository;

        public DiagnosisController(IDiagnosisRepository diagnosisRepository)
        {
            _diagnosisRepository = diagnosisRepository;
        }

        public async Task<IActionResult> Index()
        {
            var diagnoses = await _diagnosisRepository.GetAllSortedAsync();
            return View(diagnoses);
        }

        public IActionResult Create()
        {
            var diagnosis = new Diagnosis();
            return View(diagnosis);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Diagnosis diagnosis)
        {
            if (diagnosis.Code == null && diagnosis.DiagnosisName == null)
            {
                ModelState.AddModelError("", "Хотя бы одно поле должно быть заполнено");
                return View(diagnosis);
            }

            if (_diagnosisRepository.DiagnosisExistsByName(diagnosis.DiagnosisName) ||
                _diagnosisRepository.DiagnosisExistsByCode(diagnosis.Code))
            {
                ModelState.AddModelError("DiagnosisName", "Такой диагноз уже существует.");
                return View(diagnosis);
            }

            _diagnosisRepository.Add(diagnosis);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var diagnosis = await _diagnosisRepository.GetByIdAsync(id);

            if (diagnosis == null)
            {
                return NotFound();
            }

            return View(diagnosis);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, string currentName, string currentCode, Diagnosis diagnosis)
        {
            if (diagnosis.Code == null && diagnosis.DiagnosisName == null)
            {
                ModelState.AddModelError("", "Хотя бы одно поле должно быть заполнено");
                return View(diagnosis);
            }

            if ((currentName != diagnosis.DiagnosisName && _diagnosisRepository.DiagnosisExistsByName(diagnosis.DiagnosisName))
                || (currentCode != diagnosis.Code &&
                _diagnosisRepository.DiagnosisExistsByCode(diagnosis.Code)))
            {
                ModelState.AddModelError("DiagnosisName", "Такой диагноз уже существует.");
                diagnosis.DiagnosisName = currentName;
                diagnosis.Code = currentCode;
                return View(diagnosis);
            }

            var updatedDiagnosis = new Diagnosis
            {
                DiagnosisID = id,
                DiagnosisName = diagnosis.DiagnosisName,
                Code = diagnosis.Code
            };

            _diagnosisRepository.Update(updatedDiagnosis);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var diagnosis = await _diagnosisRepository.GetByIdAsync(id);

            if (diagnosis == null)
            {
                return NotFound();
            }

            return View(diagnosis);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var diagnosis = await _diagnosisRepository.GetByIdAsync(id);

                if (diagnosis == null)
                {
                    return NotFound();
                }

                _diagnosisRepository.Delete(diagnosis);
            }
            catch (DbUpdateException)
            {
                TempData["Error"] = "Данный диагноз нельзя удалить, так как к нему прикреплены справки студентов";
            }

            return RedirectToAction("Index");
        }
    }
}

StudentMedicalCertificateSystem/Views/Diagnosis/Create.cshtml
@model StudentMedicalCertificateSystem.Models.Diagnosis

@section Scripts {
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Подключение Bootstrap-select CSS и JS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
}

<div class="container">
    <a asp-action="Index">Назад ко всем диагнозам</a>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Добавление нового диагноза</h2>
            <div class="card">
                <div class="card-body">
                    <form asp-action="Create" method="post" enctype="multipart/form-data">
                        @Html.AntiForgeryToken()
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="DiagnosisName" class="control-label">Введите наименование диагноза</label>
                            <input asp-for="DiagnosisName" class="form-control" />
                            <span asp-validation-for="DiagnosisName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Code" class="control-label">Введите код диагноза</label>
                            <input asp-for="Code" class="form-control" />
                            <span asp-validation-for="Code" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Создать</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

StudentMedicalCertificateSystem/Views/Diagnosis/Delete.cshtml
@model StudentMedicalCertificateSystem.Models.Diagnosis
<div class="container">
    <div>
        <h2>Вы уверены, что хотите удалить этот диагноз?</h2>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Наименование диагноза
            </dt>
            <dd class="col-sm-10">
                @(!string.IsNullOrEmpty(Model.DiagnosisName) ? Model.DiagnosisName : "Нет")
            </dd>

            <dt class="col-sm-2">
                Код МКБ
            </dt>
            <dd class="col-sm-10">
                @(!string.IsNullOrEmpty(Model.Code) ? Model.Code : "Нет")
            </dd>
        </dl>

        <br />

        <form asp-action="Delete" method="post">
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="hidden" asp-for="DiagnosisID" />
                <input type="submit" value="Удалить" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-secondary">Отменить</a>
            </div>
        </form>
    </div>
</div>

<style>
    dl.row {
        width: 100%;
        margin: 0;
        border-spacing: 0;
        border-collapse: separate;
    }

    dt {
        display: table-cell;
        padding: 10px;
        border: 1px solid #dee2e6;
    }

    dt {
        font-weight: bold;
    }

    dd {
        padding-top: 10px;
    }

</style>

StudentMedicalCertificateSystem/Views/Diagnosis/Edit.cshtml
@model StudentMedicalCertificateSystem.Models.Diagnosis

@section Scripts {
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Подключение Bootstrap-select CSS и JS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
}

<div class="container">
    <a asp-action="Index">Назад ко всем диагнозам</a>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Редактирование диагноза</h2>
            <div class="card">
                <div class="card-body">
                    <form asp-action="Edit" method="post" enctype="multipart/form-data">
                        @Html.AntiForgeryToken()
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <input hidden name="currentName" class="form-control" value="@Model.DiagnosisName" />
                        <input hidden name="currentCode" class="form-control" value="@Model.Code" />

                        <div class="form-group">
                            <label asp-for="DiagnosisName" class="control-label">Введите наименование диагноза</label>
                            <input asp-for="DiagnosisName" class="form-control" />
                            <span asp-validation-for="DiagnosisName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Code" class="control-label">Введите код диагноза</label>
                            <input asp-for="Code" class="form-control" />
                            <span asp-validation-for="Code" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Изменить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

StudentMedicalCertificateSystem/Views/Diagnosis/Index.cshtml
@model IEnumerable<StudentMedicalCertificateSystem.Models.Diagnosis>

@{
    ViewData["Title"] = "Диагнозы";
}

<div class="container">
    <div>
        <a class="btn btn-sm btn-primary" href="@Url.Action("Create")">Добавить новый диагноз</a>
    </div>

    @if (TempData["Error"] != null)
    {
        <div class="col-md-12 alert alert-danger" style="margin-top: 20px;">
            <span><b>Извините!</b> - @TempData["Error"]</span>
        </div>
    }

    <div style="margin-top: 20px;">
        @if (Model.Count() != 0)
        {
            <table>
                <thead>
                <th>Наименование диагноза</th>
                <th>Код МКБ</th>
                <th>Действия</th>
                </thead>
                <tbody>
                    @foreach (var diagnosis in Model)
                    {
                        <tr>
                            <td>@diagnosis.DiagnosisName</td>
                            <td>@diagnosis.Code</td>
                            <td>
                                <a asp-controller="Diagnosis" asp-action="Edit" asp-route-id="@diagnosis.DiagnosisID" class="btn btn-sm btn-secondary">Редактировать</a>
                                <a asp-controller="Diagnosis" asp-action="Delete" asp-route-id="@diagnosis.DiagnosisID" class="btn btn-sm btn-danger">Удалить</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Увы, но ничего не найдено</p>
        }
    </div>
</div>

<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    td:nth-child(3) {
        white-space: nowrap;
    }

</style>