StudentMedicalCertificateSystem/Models/Clinic.cs
using System.ComponentModel.DataAnnotations;

namespace StudentMedicalCertificateSystem.Models
{
    public class Clinic
    {
        [Key]
        public int ClinicID { get; set; }
        [Required(ErrorMessage = "Необходимо ввести наименование больницы")]
        public string? ClinicName { get; set; }
    }
}

StudentMedicalCertificateSystem/Models/Clinics.cs
using System.ComponentModel.DataAnnotations;

namespace StudentMedicalCertificateSystem.Models
{
    public class Clinics
    {
        [Key]
        public int ClinicID { get; set; }
        public string? ClinicName { get; set; }
    }
}

StudentMedicalCertificateSystem/Controllers/ClinicController.cs
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudentMedicalCertificateSystem.Interfaces;
using StudentMedicalCertificateSystem.Models;

namespace StudentMedicalCertificateSystem.Controllers
{
    [Authorize(Policy = "UserOrAdminPolicy")]
    public class ClinicController : Controller
    {
        private readonly IClinicRepository _clinicRepository;

        public ClinicController(IClinicRepository clinicRepository)
        {
            _clinicRepository = clinicRepository;
        }

        public async Task<IActionResult> Index()
        {
            var clinics = await _clinicRepository.GetAllSortedAsync();
            return View(clinics);
        }

        public IActionResult Create()
        {
            var clinic = new Clinic();
            return View(clinic);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Clinic clinic)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Произошла ошибка");
                return View(clinic);
            }

            if (_clinicRepository.ClinicExists(clinic.ClinicName))
            {
                ModelState.AddModelError("ClinicName", "Такая больница уже существует.");
                return View(clinic);
            }

            _clinicRepository.Add(clinic);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var clinic = await _clinicRepository.GetByIdAsync(id);

            if (clinic == null) 
            {
                return NotFound();
            }

            return View(clinic);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, string currentName, Clinic clinic)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Произошла ошибка");
                return View(clinic);
            }

            if (currentName != clinic.ClinicName && _clinicRepository.ClinicExists(clinic.ClinicName))
            {
                ModelState.AddModelError("ClinicName", "Такая больница уже существует.");
                clinic.ClinicName = currentName;
                return View(clinic);
            }

            var updatedClinic = new Clinic
            {
                ClinicID = id,
                ClinicName = clinic.ClinicName
            };

            _clinicRepository.Update(updatedClinic);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var clinic = await _clinicRepository.GetByIdAsync(id);

            if (clinic == null)
            {
                return NotFound();
            }

            return View(clinic);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var clinic = await _clinicRepository.GetByIdAsync(id);

                if (clinic == null)
                {
                    return NotFound();
                }

                _clinicRepository.Delete(clinic);
            }
            catch (DbUpdateException)
            {
                TempData["Error"] = "Данную больницу нельзя удалить, так как к ней прикреплены справки студентов";
            }

            return RedirectToAction("Index");
        }

    }
}

StudentMedicalCertificateSystem/Views/Clinic/Create.cshtml
@model StudentMedicalCertificateSystem.Models.Clinic

@section Scripts {
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Подключение Bootstrap-select CSS и JS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
}


<div class="container">
    <a asp-action="Index">Назад ко всем больницам</a>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Добавление новой больницы</h2>
            <div class="card">
                <div class="card-body">
                    <form asp-action="Create" method="post" enctype="multipart/form-data">
                        @Html.AntiForgeryToken()
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="ClinicName" class="control-label">Введите название больницы</label>
                            <input asp-for="ClinicName" class="form-control" />
                            <span asp-validation-for="ClinicName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Создать</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

StudentMedicalCertificateSystem/Views/Clinic/Delete.cshtml
@model StudentMedicalCertificateSystem.Models.Clinic
<div class="container">
    <div>
        <h2>Вы уверены, что хотите удалить эту больницу?</h2>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Наименование больницы
            </dt>
            <dd class="col-sm-10">
                @Model.ClinicName
            </dd>
        </dl>

        <br />

        <form asp-action="Delete" method="post">
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="hidden" asp-for="ClinicID" />
                <input type="submit" value="Удалить" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-secondary">Отменить</a>
            </div>
        </form>
    </div>
</div>

<style>
    dl.row {
        width: 100%;
        margin: 0;
        border-spacing: 0;
        border-collapse: separate;
    }

    dt {
        display: table-cell;
        padding: 10px;
        border: 1px solid #dee2e6;
    }

    dt {
        font-weight: bold;
    }

    dd {
        padding-top: 10px;
    }

</style>

StudentMedicalCertificateSystem/Views/Clinic/Edit.cshtml
@model StudentMedicalCertificateSystem.Models.Clinic

@section Scripts {
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Подключение Bootstrap-select CSS и JS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
}

<div class="container">
    <a asp-action="Index">Назад ко всем больницам</a>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Редактирование больницы</h2>
            <div class="card">
                <div class="card-body">
                    <form asp-action="Edit" method="post" enctype="multipart/form-data">
                        @Html.AntiForgeryToken()
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <input hidden name="currentName" class="form-control" value="@Model.ClinicName" />

                        <div class="form-group">
                            <label asp-for="ClinicName" class="control-label">Введите наименование больницы</label>
                            <input asp-for="ClinicName" class="form-control" />
                            <span asp-validation-for="ClinicName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Изменить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

StudentMedicalCertificateSystem/Views/Clinic/Index.cshtml
@model IEnumerable<StudentMedicalCertificateSystem.Models.Clinic>

@{
    ViewData["Title"] = "Больницы";
}

<div class="container">
    <div>
        <a class="btn btn-sm btn-primary" href="@Url.Action("Create")">Добавить новую больницу</a>
    </div>

    @if (TempData["Error"] != null)
    {
        <div class="col-md-12 alert alert-danger" style="margin-top: 20px;">
            <span><b>Извините!</b> - @TempData["Error"]</span>
        </div>
    }

    <div style="margin-top: 20px;">
        @if (Model.Count() != 0)
        {
            <table>
                <thead>
                <th>Наименование больницы</th>
                <th>Действия</th>
                </thead>
                <tbody>
                    @foreach (var clinic in Model)
                    {
                        <tr>
                            <td>@clinic.ClinicName</td>
                            <td>
                                <a asp-controller="Clinic" asp-action="Edit" asp-route-id="@clinic.ClinicID" class="btn btn-sm btn-secondary">Редактировать</a>
                                <a asp-controller="Clinic" asp-action="Delete" asp-route-id="@clinic.ClinicID" class="btn btn-sm btn-danger">Удалить</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Увы, но ничего не найдено</p>
        }
    </div>
</div>

<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    td:nth-child(3) {
        white-space: nowrap;
    }

</style>