StudentMedicalCertificateSystem/Models/StudentGroup.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading.Tasks.Dataflow;

namespace StudentMedicalCertificateSystem.Models
{
    public class StudentGroup
    {
        [Key]
        public int GroupID { get; set; }
        [ForeignKey("EducationalProgram")]
        [Required(ErrorMessage = "Необходимо выбрать образовательную программу")]
        public int? ProgramID {  get; set; }
        public virtual EducationalProgram? Program { get; set; }
        [Required(ErrorMessage = "Необходимо ввести наименование группы")]
        [RegularExpression(@"^[А-ЯA-Zа-яa-z]+-\d{2}-\d+$", ErrorMessage = "Неверный формат наименования группы. Правильный формат: аббревиатура программы-две последние цифры года-номер.")]
        public string? GroupName { get; set; }

    }
}

StudentMedicalCertificateSystem/Models/StudentGroups.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks.Dataflow;

namespace StudentMedicalCertificateSystem.Models
{
    public class StudentGroups
    {
        [Key]
        public int GroupID { get; set; }
        public string? GroupName { get; set; }
    }
}

StudentMedicalCertificateSystem/Controllers/StudentGroupController.cs
using DocumentFormat.OpenXml.Drawing;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentMedicalCertificateSystem.Interfaces;
using StudentMedicalCertificateSystem.Models;

namespace StudentMedicalCertificateSystem.Controllers
{
    [Authorize(Policy = "UserOrAdminPolicy")]
    public class StudentGroupController : Controller
    {
        private readonly IStudentGroupRepository _groupRepository;
        private readonly IEducationalProgramRepository _programRepository;

        public StudentGroupController(IStudentGroupRepository groupRepository,
            IEducationalProgramRepository programRepository)
        {
            _groupRepository = groupRepository;
            _programRepository = programRepository;
        }

        public async Task<IActionResult> Index()
        {
            var groups = await _groupRepository.GetAllSortedAsync();
            return View(groups);
        }

        private async Task<List<SelectListItem>> GetPrograms()
        {
            return await _programRepository.GetProgramsAsSelectListAsync();
        }

        public async Task<IActionResult> Create()
        {
            var group = new StudentGroup();
            ViewBag.ProgramList = new SelectList(await GetPrograms(), "Value", "Text");
            return View(group);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StudentGroup group)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Произошла ошибка");
                ViewBag.ProgramList = new SelectList(await GetPrograms(), "Value", "Text");
                return View(group);
            }

            if (_groupRepository.GroupExists(group.GroupName))
            {
                ModelState.AddModelError("GroupName", "Такая группа уже существует.");
                ViewBag.ProgramList = new SelectList(await GetPrograms(), "Value", "Text");
                return View(group);
            }

            _groupRepository.Add(group);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var group = await _groupRepository.GetByIdAsync(id);

            if (group == null)
            {
                return NotFound();
            }

            ViewBag.ProgramList = new SelectList(await GetPrograms(), "Value", "Text");
            return View(group);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, string currentName, StudentGroup group)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Произошла ошибка");
                ViewBag.ProgramList = new SelectList(await GetPrograms(), "Value", "Text");
                return View(group);
            }

            if (currentName != group.GroupName && _groupRepository.GroupExists(group.GroupName))
            {
                ModelState.AddModelError("GroupName", "Такая группа уже существует.");
                ViewBag.ProgramList = new SelectList(await GetPrograms(), "Value", "Text");
                group.GroupName = currentName;
                return View(group);
            }

            var updatedGroup = new StudentGroup
            {
                GroupID = id,
                ProgramID = group.ProgramID,
                GroupName = group.GroupName
            };

            _groupRepository.Update(updatedGroup);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var group = await _groupRepository.GetByIdAsync(id);

            if (group == null)
            {
                return NotFound();
            }

            return View(group);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var group = await _groupRepository.GetByIdAsync(id);

            if (group == null)
            {
                return NotFound();
            }

            _groupRepository.Delete(group);

            return RedirectToAction("Index");
        }
    }
}

StudentMedicalCertificateSystem/Views/StudentGroup/Create.cshtml
@model StudentMedicalCertificateSystem.Models.StudentGroup

@section Scripts {
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Подключение Bootstrap-select CSS и JS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
}


<div class="container">
    <a asp-action="Index">Назад ко всем группам</a>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Добавление новой группы</h2>
            <div class="card">
                <div class="card-body">
                    <form asp-action="Create" method="post" enctype="multipart/form-data">
                        @Html.AntiForgeryToken()
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="GroupName" class="control-label">Введите наименование группы</label>
                            <input asp-for="GroupName" class="form-control" />
                            <span asp-validation-for="GroupName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="ProgramID" class="control-label">Выберите образовательную программу</label>
                            <select id="studentSelect" asp-for="ProgramID" class="form-control selectpicker" data-live-search="true">
                                <option value="">Выберите программу</option>
                                @foreach (var program in ViewBag.ProgramList)
                                {
                                    <option value="@program.Value">@program.Text</option>
                                }
                            </select>
                            <span asp-validation-for="ProgramID" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Создать</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

StudentMedicalCertificateSystem/Views/StudentGroup/Delete.cshtml
@model StudentMedicalCertificateSystem.Models.StudentGroup
<div class="container">
   

    <div>
        <div class="col-md-12 alert alert-danger" style="margin-top: 20px;">
            <span style="font-size: 18px;"><b>Внимание!</b> - При удалении группы удалятся все прикрепленные к ней студенты, а за ними вслед удалятся все созданные на них справки.</span>
        </div>
        
        <h2>Вы уверены, что хотите удалить эту группу?</h2>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Наименование группы
            </dt>
            <dd class="col-sm-10">
                @Model.GroupName
            </dd>

            <dt class="col-sm-2">
                Образовательная программа
            </dt>
            <dd class="col-sm-10">
                @Model.Program.ProgramName
            </dd>
        </dl>

        <br />

        <form asp-action="Delete" method="post">
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="hidden" asp-for="GroupID" />
                <input type="submit" value="Удалить" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-secondary">Отменить</a>
            </div>
        </form>
    </div>
</div>

<style>
    dl.row {
        width: 100%;
        margin: 0;
        border-spacing: 0;
        border-collapse: separate;
    }

    dt {
        display: table-cell;
        padding: 10px;
        border: 1px solid #dee2e6;
    }

    dt {
        font-weight: bold;
    }

    dd {
        padding-top: 10px;
    }

</style>

StudentMedicalCertificateSystem/Views/StudentGroup/Edit.cshtml
@model StudentMedicalCertificateSystem.Models.StudentGroup

@section Scripts {
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Подключение Bootstrap-select CSS и JS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
}

<div class="container">
    <a asp-action="Index">Назад ко всем группам</a>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Редактирование группы</h2>
            <div class="card">
                <div class="card-body">
                    <form asp-action="Edit" method="post" enctype="multipart/form-data">
                        @Html.AntiForgeryToken()
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        
                        <input hidden name="currentName" class="form-control" value="@Model.GroupName" />

                        <div class="form-group">
                            <label asp-for="GroupName" class="control-label">Введите наименование группы</label>
                            <input asp-for="GroupName" class="form-control" />
                            <span asp-validation-for="GroupName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="ProgramID" class="control-label">Выберите образовательную программу</label>
                            <select id="studentSelect" asp-for="ProgramID" class="form-control selectpicker" data-live-search="true">
                                <option value="">Выберите программу</option>
                                @foreach (var program in ViewBag.ProgramList)
                                {
                                    <option value="@program.Value">@program.Text</option>
                                }
                            </select>
                            <span asp-validation-for="ProgramID" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Изменить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

StudentMedicalCertificateSystem/Views/StudentGroup/Index.cshtml
@model IEnumerable<StudentMedicalCertificateSystem.Models.StudentGroup>

@{
    ViewData["Title"] = "Группы";
}

<div class="container">
    <div>
        <a class="btn btn-sm btn-primary" href="@Url.Action("Create")">Добавить новую группу</a>
    </div>

    <div style="margin-top: 20px;">
        @if (Model.Count() != 0)
        {
            <table>
                <thead>
                <th>Наименование группы</th>
                <th>Образовательная программа</th>
                <th>Действия</th>
                </thead>
                <tbody>
                    @foreach (var group in Model)
                    {
                        <tr>
                            <td>@group.GroupName</td>
                            <td>@group.Program.ProgramName</td>
                            <td>
                                <a asp-controller="StudentGroup" asp-action="Edit" asp-route-id="@group.GroupID" class="btn btn-sm btn-secondary">Редактировать</a>
                                <a asp-controller="StudentGroup" asp-action="Delete" asp-route-id="@group.GroupID" class="btn btn-sm btn-danger">Удалить</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Увы, но ничего не найдено</p>
        }
    </div>
</div>

<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    td:nth-child(3) {
        white-space: nowrap;
    }

</style>